# Author: Abraham Macias Paredes
# E-mail: system252001@yahoo.es
# License: GNU GPL v2 (see LICENSE file for details).

from .grayscale import GRAYSCALE_256COLORS_PALETTE
from .metallic import METALLIC_256COLORS_PALETTE
from .ntsc import NTSC_256COLORS_PALETTE
from .pastels import PASTELS_256COLORS_PALETTE
from .rainbow import RAINBOW_256COLORS_PALETTE
from .systemMac import SYSTEM_MAC_256COLORS_PALETTE
from .systemWinDir4 import SYSTEM_WINDOWS_DIR4_256COLORS_PALETTE
from .systemWin import SYSTEM_WINDOWS_256COLORS_PALETTE
from .vivid import VIVID_256COLORS_PALETTE
from .web216 import WEB_256COLORS_PALETTE


__all__ = ['GRAYSCALE_256COLORS_PALETTE', 'METALLIC_256COLORS_PALETTE',
           'NTSC_256COLORS_PALETTE', 'PASTELS_256COLORS_PALETTE',
           'RAINBOW_256COLORS_PALETTE', 'SYSTEM_MAC_256COLORS_PALETTE',
           'SYSTEM_WINDOWS_DIR4_256COLORS_PALETTE',
           'SYSTEM_WINDOWS_256COLORS_PALETTE', 'VIVID_256COLORS_PALETTE',
           'WEB_256COLORS_PALETTE']
